CREATE DATABASE IF NOT EXISTS ADALO;
USE ADALO; 
DROP TABLE IF EXISTS region6;
CREATE TABLE region6 (
  Region TINYINT DEFAULT 6 NOT NULL,
  CellID INT UNSIGNED NOT NULL,
  DLon MEDIUMINT SIGNED NOT NULL,
  DLat MEDIUMINT SIGNED NOT NULL,
  Segment SMALLINT UNSIGNED NULL,
  PRIMARY KEY(CellID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
ALTER TABLE region6 ADD INDEX segkey (Segment);
 
DROP TABLE IF EXISTS region8;
CREATE TABLE region8 (
  Region TINYINT DEFAULT 8 NOT NULL,
  CellID INT UNSIGNED NOT NULL,
  DLon MEDIUMINT SIGNED NOT NULL,
  DLat MEDIUMINT SIGNED NOT NULL,
  Segment SMALLINT UNSIGNED NULL,
  PRIMARY KEY(CellID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
ALTER TABLE region8 ADD INDEX segkey (Segment); 

DROP TABLE IF EXISTS padus30m;
CREATE TABLE padus30m (
  CellID INT UNSIGNED NOT NULL,
  ObjectId INT UNSIGNED NULL,
  ListNum SMALLINT UNSIGNED NULL,
  KEY CellIDPad (CellID,ObjectId)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
 
DROP TABLE IF EXISTS r6padus;
CREATE TABLE r6padus (
  Region TINYINT DEFAULT 6 NOT NULL,
  CellID INT UNSIGNED NOT NULL,
  DLon MEDIUMINT SIGNED NOT NULL,
  DLat MEDIUMINT SIGNED NOT NULL,
  Segment SMALLINT UNSIGNED NULL,
  ObjectId INT UNSIGNED NULL,
  ListNum SMALLINT UNSIGNED NULL,
  PRIMARY KEY(CellID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
ALTER TABLE r6padus ADD INDEX geokey (ObjectId,Segment,DLon,DLat);

DROP TABLE IF EXISTS r8padus;
CREATE TABLE r8padus (
  Region TINYINT DEFAULT 8 NOT NULL,
  CellID INT UNSIGNED NOT NULL,
  DLon MEDIUMINT SIGNED NOT NULL,
  DLat MEDIUMINT SIGNED NOT NULL,
  Segment SMALLINT UNSIGNED NULL,
  ObjectId INT UNSIGNED NULL,
  ListNum SMALLINT UNSIGNED NULL,
  PRIMARY KEY(CellID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
ALTER TABLE r8padus ADD INDEX geokey (ObjectId,Segment,DLon,DLat);

INSERT INTO r6padus
  SELECT t1.Region, t1.CellID, t1.DLon, t1.DLat, t1.Segment, t2.ObjectId, t2.ListNum
  FROM region6 as t1 LEFT JOIN padus30m as t2 ON (t1.CellID = t2.CellID);
  
INSERT INTO r8padus
  SELECT t1.Region, t1.CellID, t1.DLon, t1.DLat, t1.Segment, t2.ObjectId, t2.ListNum
  FROM region8 as t1 LEFT JOIN padus30m as t2 ON (t1.CellID = t2.CellID);

